server:
  port: 8080
  servlet:
    context-path: /producer
app:
  demo:
    products:
      exchange: product-producer
      enhanced-exchange: product-enhancer
    orders:
      exchange: order-producer
